app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError
from app.models import User

# Profile editing form
class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=200)])
    submit = SubmitField('Submit')

    # This is needed for username change to work!
    # Not exactly sure what this does,
    # but it invokes the class constructor in the parent class.
    # Super is used as a shortcut to access a parent class.
    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    # Validate new username
    def validate_username(self, username):
        # Compare if username is different from previous one
        if username.data != self.original_username:
            # Query with new username, return user obj or None
            user = User.query.filter_by(username=self.username.data).first()
            # If returned user obj username is already in use
            if user is not None:
                raise ValidationError('Username already in use.')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, url_for, flash, redirect, request
from flask_login import current_user, login_required
from app.main.forms import EditProfileForm
from app.models import User
from app.main import bp
from app import db
import urllib.parse, hashlib

# Home / Index / Root route
@bp.route('/')
def home():
    return render_template('main/index.html')


# User profile route, where <username> is username for known user
@bp.route('/profile/<username>')
@login_required
def profile(username):
    # Check if user exist or return error page
    user = User.query.filter_by(username=username).first_or_404()
    # Gravatar size
    gravatar_size = 200
    # Gravatar URL
    gravatar_url = "https://www.gravatar.com/avatar/" + hashlib.md5(user.email.lower().encode('utf-8')).hexdigest() + "?"
    # Encode parameters at the end of URL. Use identicon as default avatars
    gravatar_url += urllib.parse.urlencode({'d':'identicon', 's':str(gravatar_size)})
    return render_template('main/profile.html',
                            user=user, gravatar_url=gravatar_url)


# Edit profile route
@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    # Validate username change
    if form.validate_on_submit():
        # If form is ok, commit
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Changes have been saved!')
        return redirect(url_for('main.edit_profile'))
    # When form is requested, fill in current profile info to the fields
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('main/profile_edit.html', form=form)


# Generate new API token
@bp.route('/get_api_token')
@login_required
def get_api_token():
    # Generate new API token
    current_user.gen_api_token()
    db.session.commit()
    # Redirect back to profile
    return redirect(url_for('main.profile', username=current_user.username))

app/templates/main/index.html
{% extends "template.html" %}
{% block title %} Welcome! {% endblock %}

{% block content %}

  <div class="jumbotron">
    {% if current_user.is_anonymous %}
    <h1 class="text-center">Welcome stranger!</h1>
    {% else %}
    <h1 class="text-center">Hello {{ current_user.username }}!</h1>
    {% endif %}
    <div class="msg">{{ msg }}</div>
    <p class="lead"></p>
    <div class="menu">
      {% if current_user.is_anonymous %}
      <a class="btn btn-lg btn-primary btn-block" href="{{ url_for('auth.login') }}">Login</a>
      <a class="btn btn-lg btn-primary btn-block" href="{{ url_for('auth.signup') }}">Sign Up</a>
      {% else %}
      <a class="btn btn-lg btn-primary btn-block" href="{{ url_for('auth.logout') }}">Logout</a>
      {% endif %}
    </div>
  </div>

{% endblock %}

app/templates/main/profile.html
{% extends "template.html" %}
{% block title %} Profile {% endblock %}

{% block style %}
  <style>
    img {
      outline: 1px solid black;
      max-width: 200px;
      max-height: 200px;
    }

    .main-card {
      border: 1px solid rgba(0, 0, 0, .125);
      background-color: white;
      border-radius: 1rem;
      box-shadow: 3px 3px 10px grey;
    }

    .about-card {
      border: 1px solid rgba(0, 0, 0, .125);
      background-color: white;
      border-radius: 1rem;
      box-shadow: 3px 3px 10px grey;
    }

    .card {
      background-color: rgba(219, 245, 255, 1);
    }
  </style>
{% endblock %}

{% block content %}

  <div class="card">
    <div class="row no-gutters main-card m-3">
      <div class="col-md-auto p-3">
        <img src="{{ gravatar_url }}" class="card-img">
      </div>
      <div class="col-md-auto">
        <div class="card-body">
          <p class="card-text">Name: {{ user.username }}</p>
          {% if user == current_user %}
          <p class="card-text">Email: {{ user.email }}</p>
          {% endif %}
          {% if user == current_user %}
          <p class="card-text">Signup date: {{ moment(user.signup_date).format('Do MMMM, YYYY HH:mm') }}</p>
          {% else %}
          <p class="card-text">Signup date: {{ moment(user.signup_date).format('Do MMMM, YYYY') }}</p>
          {% endif %}
          {% if user == current_user %}
          <a class="btn btn-primary" href="{{ url_for('main.edit_profile') }}">Edit Profile</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% if user.about_me %}
      <div class="about-card card-body m-3">
        {{ user.about_me }}
      </div>
    {% endif %}
    {% if user == current_user %}
      <div>
        <input type="text" value="{{ user.api_token }}" readonly>
        <a class="btn" href="{{ url_for('main.get_api_token') }}">Refresh token</a>
      </div>
    {% endif %}
  </div>

{% endblock %}

app/templates/main/profile_edit.html
{% extends "template.html" %}
{% block title %} Edit Profile {% endblock %}

{% block content %}
  <h1>Edit Profile</h1>
  <form action="" method="POST">
    {{ form.hidden_tag() }}
    <p>
      {{ form.username.label }}<br>
      {{ form.username(size=32) }}<br>
      {% for error in form.username.errors %}
      <span style="color: red;">[{{ error }}]</span>
      {% endfor %}
    </p>
    <p>
      {{ form.about_me.label }}<br>
      {{ form.about_me(cols=50, rows=5) }}<br>
      {% for error in form.about_me.errors %}
      <span style="color: red;">[{{ error }}]</span>
      {% endfor %}
    </p>
    <p>{{ form.submit }}</p>
  </form>
{% endblock %}